name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [MicroCMS_update]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1  # なくても動くがGithubPagesと統一
    - run: yarn
    - run: yarn build
    env:
      GATSBY_API_KEY: ${{ secrets.GATSBY_API_KEY }}
      GATSBY_SERVICE_ID: ${{ secrets.GATSBY_SERVICE_ID }}
      GATSBY_ADSENSE: ${{ secrets.GATSBY_ADSENSE }}

    # Only Firebase Hosting
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NOMURAYA }}'
        channelId: live
        projectId: nomuraya
      env:
        FIREBASE_CLI_PREVIEWS: hostingchannels
